### ISSUE TITLE
Installation fails (unnecessarily) for perl versions usable Math::Pari

### ISSUE THREAD

**Issue by rivy** [audreyt/module-signature#14]
As of v1.12, "Crypt::OpenPGP"  has much different module requirement, and it no longer depends on "Math::Pari", nor any module requiring "Math::Pari". The old requirements list in `Makefile.PL` is unnecessarily blocking install on 64-bit MSWin32 perl version.

Simplifying the requirement to just "Crypt::OpenPGP" should correct the issue.

**Comment by audreyt** [comment]
Released as 0.80. Thanks so much! 🌈

**Comment by rivy** [comment]
Cheers!
